services:
  db:
    image: postgres:16.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=salute
      - POSTGRES_USER=salute
      - POSTGRES_PASSWORD=salute
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  postgres_data_dev: 