# Generated by Django 5.1.5 on 2025-01-16 17:13

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Salute ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "google_id",
                    models.CharField(editable=False, max_length=100, unique=True),
                ),
                (
                    "email",
                    models.CharField(editable=False, max_length=255, unique=True),
                ),
                ("name", models.CharField(editable=False, max_length=255)),
                ("description", models.TextField(editable=False)),
                ("salute_managed", models.BooleanField(default=False, editable=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WorkspaceGroupAlias",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Salute ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "address",
                    models.EmailField(editable=False, max_length=254, unique=True),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="workspace.workspacegroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workspace Group Alias",
                "verbose_name_plural": "Workspace Group Aliases",
            },
        ),
    ]
