# Generated by Django 5.1.6 on 2025-03-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamtype",
            name="nickname",
            field=models.CharField(
                blank=True,
                help_text='Used to override name from TSA. Include "Team", e.g "People Team"',
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="teamtype",
            name="display_name",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(
                        models.Q(("nickname__exact", ""), _negated=True),
                        models.F("nickname"),
                    ),
                    default=models.F("name"),
                ),
                output_field=models.CharField(max_length=255),
            ),
        ),
        migrations.AlterModelOptions(
            name="teamtype",
            options={"ordering": ("display_name",)},
        ),
        migrations.AlterModelOptions(
            name="team",
            options={"ordering": ("team_type__display_name",)},
        ),
    ]
