# Generated by Django 5.1.6 on 2025-03-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={"ordering": ("team_type__display_name",)},
        ),
        migrations.AlterModelOptions(
            name="teamtype",
            options={"ordering": ("display_name",)},
        ),
        migrations.AddField(
            model_name="teamtype",
            name="nickname",
            field=models.CharField(
                blank=True,
                help_text='Used to override name from TSA. Include "Team", e.g "People Team"',
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="teamtype",
            name="has_all_list",
            field=models.BooleanField(
                default=False,
                help_text="If has sub-teams, whether to generate a -all list.",
            ),
        ),
        migrations.AddField(
            model_name="teamtype",
            name="has_team_lead",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="teamtype",
            name="included_in_all_members",
            field=models.BooleanField(default=True, help_text="Included in all members -all addresses"),
        ),
        migrations.AddField(
            model_name="teamtype",
            name="mailing_slug",
            field=models.CharField(
                blank=True,
                help_text="Slug for generating mailing lists. Do not change unless you understand the impact.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="teamtype",
            name="display_name",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(
                        models.Q(("nickname__exact", ""), _negated=True),
                        models.F("nickname"),
                    ),
                    default=models.F("name"),
                ),
                output_field=models.CharField(max_length=255),
            ),
        ),
    ]
