# Generated by Django 5.2.1 on 2025-05-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roles", "0002_add_fields_to_team_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamtype",
            name="members_can_send_as",
            field=models.BooleanField(default=True, help_text="If true, members can send as this team."),
        ),
        migrations.AlterField(
            model_name="teamtype",
            name="has_team_lead",
            field=models.BooleanField(default=False, help_text="If true, generate a -lead mailing list."),
        ),
    ]
