# Generated by Django 5.2.3 on 2025-07-05 16:49

import django_choices_field.fields
from django.db import migrations

import salute.roles.models


class Migration(migrations.Migration):
    dependencies = [
        ("roles", "0003_add_members_can_send_as_to_team_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="level",
            field=django_choices_field.fields.TextChoicesField(  # type: ignore[call-overload]
                choices=[
                    ("DISTRICT", "District"),
                    ("GROUP", "Group"),
                    ("SECTION", "Section"),
                ],
                choices_enum=salute.roles.models.TeamLevel,
                editable=False,
                max_length=8,
                null=True,
            ),
        ),
    ]
