# Generated by Django 5.2.3 on 2025-08-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roles", "0004_add_team_level_field"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="roletype",
            options={"ordering": ("-display_priority", "name")},
        ),
        migrations.AlterModelOptions(
            name="role",
            options={"ordering": ("role_type", "team", "person")},
        ),
        migrations.AddField(
            model_name="roletype",
            name="display_priority",
            field=models.PositiveIntegerField(default=100, help_text="Used to order roles in the UI."),
        ),
    ]
