# Generated by Django 5.2.3 on 2025-08-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roles", "0005_add_role_type_display_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="related_teams",
            field=models.ManyToManyField(blank=True, to="roles.team"),
        ),
    ]
