# Generated by Django 5.2.3 on 2025-08-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roles", "0006_add_related_teams"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamtype",
            name="description",
            field=models.TextField(blank=True, help_text="Description of the team as markdown"),
        ),
    ]
