# Generated by Django 5.2.3 on 2025-10-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roles", "0007_add_team_type_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamtype",
            name="mailing_name_prefix_for_district_teams",
            field=models.BooleanField(
                default=True,
                help_text='If true, prefix the mailing list name with "District" for district teams.',
            ),
        ),
    ]
