# Generated by Django 5.2.3 on 2026-01-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roles", "0008_teamtype_mailing_name_prefix_for_district_teams"),
    ]

    operations = [
        migrations.AddField(
            model_name="roletype",
            name="included_in_census",
            field=models.BooleanField(
                default=False,
                help_text="If true, the role is included in the census as an adult volunteer.",
            ),
        ),
        migrations.AddField(
            model_name="roletype",
            name="is_member_role",
            field=models.BooleanField(
                default=False,
                help_text="If true, the role is a member role. Used for emails and other communications to members.",
            ),
        ),
    ]
