# Generated by Django 5.2.3 on 2026-01-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roles", "0009_add_role_type_category_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="roletype",
            name="is_youth_member",
            field=models.BooleanField(
                default=False,
                help_text="If true, the role is a youth member role (e.g., Network Member). Used for member count calculations.",  # noqa: E501
            ),
        ),
    ]
