# Generated by Django 5.2.10 on 2026-03-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roles", "0010_add_is_youth_member_to_role_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="roletype",
            name="mailing_list_filterable",
            field=models.BooleanField(
                default=True,
                help_text="If true, this role can be used to filter mailing lists.",
            ),
        ),
        migrations.AddField(
            model_name="teamtype",
            name="mailing_list_filterable",
            field=models.BooleanField(
                default=True,
                help_text="If true, this team type can be used to filter mailing lists.",
            ),
        ),
    ]
