# Generated by Django 5.2.17 on 2026-09-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roles", "0011_add_mailing_list_filterable"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamtype",
            name="display_automatic_roles_by_default",
            field=models.BooleanField(
                default=False,
                help_text="If true, display automatic roles for this team type by default.",
            ),
        ),
    ]
