# Generated by Django 5.1.7 on 2025-03-30 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing_groups", "0001_initial"),
        ("workspace", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workspacegroup",
            name="salute_managed",
        ),
        migrations.AddField(
            model_name="workspacegroup",
            name="system_mailing_group",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workspace_group",
                to="mailing_groups.systemmailinggroup",
            ),
        ),
    ]
