# Generated by Django 5.1.5 on 2025-02-01 11:33

import uuid

import django.db.models.deletion
import django_choices_field.fields
from django.db import migrations, models

import salute.hierarchy.constants


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Salute ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tsa_id",
                    models.UUIDField(editable=False, unique=True, verbose_name="TSA ID"),
                ),
                (
                    "tsa_last_modified",
                    models.DateTimeField(editable=False, verbose_name="TSA Last Modified at"),
                ),
                ("unit_name", models.CharField(editable=False, max_length=255)),
                ("shortcode", models.CharField(editable=False, max_length=9)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Salute ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tsa_id",
                    models.UUIDField(editable=False, unique=True, verbose_name="TSA ID"),
                ),
                (
                    "tsa_last_modified",
                    models.DateTimeField(editable=False, verbose_name="TSA Last Modified at"),
                ),
                ("unit_name", models.CharField(editable=False, max_length=255)),
                ("shortcode", models.CharField(editable=False, max_length=9)),
                (
                    "group_type",
                    django_choices_field.fields.TextChoicesField(  # type: ignore[call-overload]
                        choices=[("Air", "Air"), ("Land", "Land"), ("Sea", "Sea")],
                        choices_enum=salute.hierarchy.constants.GroupType,
                        editable=False,
                        max_length=4,
                    ),
                ),
                (
                    "charity_number",
                    models.PositiveIntegerField(editable=False, null=True),
                ),
                ("local_unit_number", models.PositiveSmallIntegerField(unique=True)),
                ("location_name", models.CharField(max_length=255)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="groups",
                        to="hierarchy.district",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Salute ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tsa_id",
                    models.UUIDField(editable=False, unique=True, verbose_name="TSA ID"),
                ),
                (
                    "tsa_last_modified",
                    models.DateTimeField(editable=False, verbose_name="TSA Last Modified at"),
                ),
                ("unit_name", models.CharField(editable=False, max_length=255)),
                ("shortcode", models.CharField(editable=False, max_length=9)),
                (
                    "section_type",
                    django_choices_field.fields.TextChoicesField(  # type: ignore[call-overload]
                        choices=[
                            ("Squirrels", "Squirrels"),
                            ("Beavers", "Beavers"),
                            ("Cubs", "Cubs"),
                            ("Scouts", "Scouts"),
                            ("Explorers", "Explorers"),
                            ("Young Leader", "Young Leaders"),
                            ("Network", "Network"),
                        ],
                        choices_enum=salute.hierarchy.constants.SectionType,
                        editable=False,
                        max_length=12,
                    ),
                ),
                (
                    "usual_weekday",
                    django_choices_field.fields.TextChoicesField(  # type: ignore[call-overload]
                        choices=[
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("saturday", "Saturday"),
                            ("sunday", "Sunday"),
                        ],
                        choices_enum=salute.hierarchy.constants.Weekday,
                        max_length=9,
                        null=True,
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sections",
                        to="hierarchy.district",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sections",
                        to="hierarchy.group",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("district__isnull", False),
                                ("group__isnull", True),
                                (
                                    "section_type__in",
                                    ["Explorers", "Young Leader", "Network"],
                                ),
                            ),
                            models.Q(
                                ("district__isnull", True),
                                ("group__isnull", False),
                                (
                                    "section_type__in",
                                    ["Squirrels", "Beavers", "Cubs", "Scouts"],
                                ),
                            ),
                            _connector="OR",
                        ),
                        name="section_is_either_group_or_district",
                        violation_error_message="A section must be associated with one group or district.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("usual_weekday__isnull", False),
                            ("section_type__in", ["Young Leader", "Network"]),
                            _connector="OR",
                        ),
                        name="regular_sections_must_have_usual_weekday",
                        violation_error_message="A section must have a usual weekday, unless it is network or young leaders",  # noqa: E501
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            (
                                "section_type__in",
                                ["Squirrels", "Beavers", "Cubs", "Scouts"],
                            )
                        ),
                        fields=("group", "section_type", "usual_weekday"),
                        name="ensure_only_one_section_type_per_weekday_per_group",
                        violation_error_message="Only one group section of each type can be on a given weekday",
                    ),
                ],
            },
        ),
    ]
