# Generated by Django 5.1.5 on 2025-01-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hierarchy", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="section",
            name="section_is_either_group_or_district",
        ),
        migrations.AlterField(
            model_name="section",
            name="section_type",
            field=models.CharField(
                choices=[
                    ("Squirrels", "Squirrels"),
                    ("Beavers", "Beavers"),
                    ("Cubs", "Cubs"),
                    ("Scouts", "Scouts"),
                    ("Explorers", "Explorers"),
                    ("Young Leader", "Young Leaders"),
                    ("Network", "Network"),
                ],
                editable=False,
                max_length=12,
            ),
        ),
        migrations.AddConstraint(
            model_name="section",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("district__isnull", False),
                        ("group__isnull", True),
                        ("section_type__in", ["Explorers", "Young Leader", "Network"]),
                    ),
                    models.Q(
                        ("district__isnull", True),
                        ("group__isnull", False),
                        (
                            "section_type__in",
                            ["Squirrels", "Beavers", "Cubs", "Scouts"],
                        ),
                    ),
                    _connector="OR",
                ),
                name="section_is_either_group_or_district",
                violation_error_message="A section must be associated with one group or district.",
            ),
        ),
    ]
