# Generated by Django 5.2.1 on 2025-05-19 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hierarchy", "0003_add_locality_to_groups"),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="primary_site",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="groups",
                to="locations.site",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sections",
                to="locations.site",
            ),
        ),
    ]
