# Generated by Django 5.2.3 on 2025-08-15 16:41

from django.db import migrations

import salute.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("hierarchy", "0004_add_primary_site_to_groups_and_sections"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="usual_meeting_slot",
            field=salute.core.fields.TimeRangeField(blank=True, null=True),
        ),
    ]
