# Generated by Django 5.2.3 on 2025-08-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hierarchy", "0005_section_usual_meeting_slot"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="osm_id",
            field=models.CharField(
                verbose_name="OSM ID",
                blank=True,
                null=True,
                unique=True,
                help_text="The ID of the section in Online Scout Manager. Do not change unless you understand the impact.",  # noqa: E501
                max_length=255,
            ),
        ),
    ]
