# Generated by Django 5.1.5 on 2025-02-01 09:28

import uuid

import django.db.models.functions.text
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Salute ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tsa_id",
                    models.UUIDField(editable=False, unique=True, verbose_name="TSA ID"),
                ),
                ("legal_name", models.CharField(editable=False, max_length=255)),
                ("preferred_name", models.CharField(editable=False, max_length=255)),
                ("last_name", models.CharField(editable=False, max_length=255)),
                (
                    "membership_number",
                    models.PositiveIntegerField(editable=False, unique=True, verbose_name="Membership Number"),
                ),
                ("is_suspended", models.BooleanField(editable=False)),
                ("primary_email", models.EmailField(blank=True, editable=False, max_length=254)),
                ("default_email", models.EmailField(blank=True, editable=False, max_length=254)),
                ("alternate_email", models.EmailField(blank=True, editable=False, max_length=254)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        editable=False, max_length=128, null=True, region=None
                    ),
                ),
                (
                    "alternate_phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        editable=False, max_length=128, null=True, region=None
                    ),
                ),
                (
                    "first_name",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Case(
                            models.When(
                                models.Q(("preferred_name__exact", ""), _negated=True),
                                models.F("preferred_name"),
                            ),
                            default=models.F("legal_name"),
                        ),
                        output_field=models.CharField(max_length=511),
                    ),
                ),
                (
                    "display_name",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.text.Concat(
                            models.Case(
                                models.When(~models.Q(preferred_name__exact=""), models.F("preferred_name")),
                                default=models.F("legal_name"),
                            ),
                            models.Value(" "),
                            models.F("last_name"),
                        ),
                        output_field=models.CharField(max_length=511),
                    ),
                ),
                (
                    "tsa_email",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Case(
                            models.When(
                                models.Q(("primary_email__exact", ""), _negated=True),
                                models.F("primary_email"),
                            ),
                            models.When(
                                models.Q(("default_email__exact", ""), _negated=True),
                                models.F("default_email"),
                            ),
                            models.When(
                                models.Q(("alternate_email__exact", ""), _negated=True),
                                models.F("alternate_email"),
                            ),
                            default=models.Value(None),
                        ),
                        output_field=models.EmailField(max_length=254),
                    ),
                ),
            ],
            options={
                "ordering": ("display_name", "membership_number"),
                "verbose_name": "Person",
                "verbose_name_plural": "People",
            },
        ),
    ]
