# Generated by Django 5.2.3 on 2026-01-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="tsa_email",
        ),
        migrations.RemoveField(
            model_name="person",
            name="primary_email",
        ),
        migrations.AddField(
            model_name="person",
            name="tsa_email",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(
                        models.Q(("alternate_email__exact", ""), _negated=True),
                        models.F("alternate_email"),
                    ),
                    models.When(
                        models.Q(("default_email__exact", ""), _negated=True),
                        models.F("default_email"),
                    ),
                    default=models.Value(None),
                ),
                output_field=models.EmailField(max_length=254),
                verbose_name="TSA Preferred Email",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="alternate_email",
            field=models.EmailField(
                blank=True,
                editable=False,
                max_length=254,
                verbose_name="TSA Communication Email",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="default_email",
            field=models.EmailField(
                blank=True,
                editable=False,
                max_length=254,
                verbose_name="TSA Login Email",
            ),
        ),
    ]
