# Generated by Django 5.2.10 on 2026-05-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0004_add_permit_activity_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="is_young_person",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
