# Generated by Django 5.2.10 on 2026-09-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0005_add_is_young_person_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="days_of_service_recording",
            field=models.PositiveIntegerField(
                editable=False,
                help_text="Number of days of service recorded in TSA.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="days_of_service_recording_last_updated",
            field=models.DateField(
                editable=False,
                help_text="The last date that the days of service recording was updated from TSA.",
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("days_of_service_recording__isnull", True),
                        ("days_of_service_recording_last_updated__isnull", True),
                    ),
                    models.Q(
                        ("days_of_service_recording__isnull", False),
                        ("days_of_service_recording_last_updated__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="person_days_of_service_recording_last_updated_check",
            ),
        ),
    ]
