# Generated by Django 5.2.1 on 2025-05-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="site",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="site",
            name="include_in_centroid_calculation",
            field=models.BooleanField(
                default=True,
                help_text="Whether to include this site in centroid calculations for map display.",
                verbose_name="Included in centroid calculation",
            ),
        ),
    ]
