# Generated by Django 5.1.5 on 2025-02-15 18:23

import uuid

import django.db.models.deletion
import django_choices_field.fields
from django.conf import settings
from django.db import migrations, models

import salute.accounts.models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("hierarchy", "0001_initial"),
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="person",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="people.person",
            ),
        ),
        migrations.CreateModel(
            name="DistrictUserRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Salute ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "level",
                    django_choices_field.fields.TextChoicesField(
                        choices=[("Admin", "Admin"), ("Manager", "Manager")],  # type: ignore[call-overload]
                        choices_enum=salute.accounts.models.DistrictUserRoleType,
                        max_length=7,
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="hierarchy.district",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="district_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "district"),
                        name="one_district_role_per_user",
                        violation_error_message="A user can only have one district role",
                    )
                ],
            },
        ),
    ]
