# Generated by Django 5.1.7 on 2025-03-16 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_add_permissions_fields"),
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth0_sub",
            field=models.CharField(
                blank=True,
                help_text="Do not edit if you do not understand. Maps to sub in OIDC token",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Auth0 Subject",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="person",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="people.person",
            ),
        ),
    ]
