# Generated by Django 5.2.10 on 2026-05-18 16:39

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_add_auth0_sub_field"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("people", "0004_add_permit_activity_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Salute ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="user",
            name="service_account",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user",
                to="accounts.serviceaccount",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("service_account__isnull", True),
                    models.Q(("person__isnull", True), ("service_account__isnull", False)),
                    _connector="OR",
                ),
                name="user_must_have_only_one_account_type",
                violation_error_message="A user must have either a service account or a person, but not both.",
            ),
        ),
    ]
