# Generated by Django 5.2.10 on 2026-01-23 22:42

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hierarchy", "0006_add_osm_id_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaitingListSectionTypeRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Salute ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("TOO_YOUNG", "Too Young"),
                            ("TOO_OLD", "Too Old"),
                            ("SQUIRRELS", "Squirrels"),
                            ("BEAVERS", "Beavers"),
                            ("CUBS", "Cubs"),
                            ("SCOUTS", "Scouts"),
                            ("EXPLORERS", "Explorers"),
                            ("NETWORK", "Network"),
                        ],
                        max_length=30,
                    ),
                ),
                ("date", models.DateField()),
                ("waiting_list_count", models.IntegerField()),
            ],
            options={
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("section_type", "date"),
                        name="unique_waiting_list_section_type_date",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WaitingListUnit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Salute ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="waiting_list_units",
                        to="hierarchy.group",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="waiting_list_units",
                        to="hierarchy.section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Waiting List Unit",
                "verbose_name_plural": "Waiting List Units",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WaitingListSectionRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Salute ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("waiting_list_count", models.IntegerField()),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="hierarchy.section",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("section", "date"),
                        name="unique_waiting_list_section_date",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WaitingListEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Salute ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(max_length=255, unique=True)),
                ("joined_waiting_list_at", models.DateTimeField(db_index=True)),
                (
                    "date_of_birth",
                    models.DateField(help_text="Rounded to the first of the month"),
                ),
                ("postcode", models.CharField(max_length=255)),
                ("successfully_transferred", models.BooleanField()),
                (
                    "units",
                    models.ManyToManyField(
                        related_name="waiting_list_entries",
                        to="waiting_list.waitinglistunit",
                    ),
                ),
            ],
            options={
                "ordering": ["-joined_waiting_list_at"],
                "indexes": [
                    models.Index(fields=["date_of_birth"], name="waiting_lis_date_of_e85cb2_idx"),
                    models.Index(fields=["postcode"], name="waiting_lis_postcod_03777d_idx"),
                    models.Index(
                        fields=["successfully_transferred"],
                        name="waiting_lis_success_bedf8e_idx",
                    ),
                ],
            },
        ),
    ]
