# Generated by Django 5.2.1 on 2025-05-26 13:40

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hierarchy", "0004_add_primary_site_to_groups_and_sections"),
        ("mailing_groups", "0002_add_fallback_groups"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupSectionSystemMailingPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Salute ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("Squirrels", "Squirrels"),
                            ("Beavers", "Beavers"),
                            ("Cubs", "Cubs"),
                            ("Scouts", "Scouts"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "mailing_preference",
                    models.CharField(
                        choices=[
                            ("TEAMS", "Teams (Recommended, Default)"),
                            ("LEADERS", "Team Leaders"),
                        ],
                        default="TEAMS",
                        max_length=32,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hierarchy.group",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("group", "section_type"),
                        name="unique_group_section_type",
                        violation_error_message="Mailing preference already exists for this group and section type.",
                    )
                ],
            },
        ),
    ]
