# Generated by Django 5.2.1 on 2025-05-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing_groups", "0003_add_group_mailing_preferences"),
        ("roles", "0002_add_fields_to_team_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemmailinggroup",
            name="teams",
            field=models.ManyToManyField(
                blank=True,
                editable=False,
                help_text="The teams that this mailing group belongs to.",
                related_name="system_mailing_groups",
                to="roles.team",
            ),
        ),
    ]
