# Generated by Django 5.2.1 on 2025-05-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing_groups", "0004_add_system_mailing_group_team_relation"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemmailinggroup",
            name="short_name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
