# Generated by Django 5.2.10 on 2026-03-25 19:01

import uuid

import django.db.models.deletion
import django_choices_field.fields
from django.db import migrations, models

import salute.integrations.email_octopus.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("people", "0002_fix_tsa_email_priority"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailOctopusContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Salute ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact_id",
                    models.UUIDField(unique=True, verbose_name="Email Octopus Contact ID"),
                ),
                (
                    "status",
                    django_choices_field.fields.TextChoicesField(
                        choices_enum=salute.integrations.email_octopus.models.EmailOctopusStatus,
                        default="subscribed",
                        editable=False,
                        max_length=12,
                    ),
                ),
                (
                    "person",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_octopus_contact",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
