# Generated by Django 5.2.3 on 2025-08-23 19:54

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roles", "0007_add_team_type_description"),
        ("stats", "0002_add_section_census_return"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamSummaryRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Salute ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("total_people", models.IntegerField()),
                ("count_by_role_type", models.JSONField()),
                ("count_by_role_status", models.JSONField()),
                ("count_by_accreditation_type", models.JSONField()),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="summary_records",
                        to="roles.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [models.Index(fields=["date"], name="idx_teamsummaryrecord_date")],
                "constraints": [models.UniqueConstraint(fields=("team", "date"), name="unique_team_date")],
            },
        ),
    ]
