# Generated by Django 5.2.3 on 2025-11-23 23:26

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hierarchy", "0006_add_osm_id_field"),
        ("stats", "0003_add_team_summary_record"),
    ]

    operations = [
        migrations.CreateModel(
            name="DistrictSummaryRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Salute ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("total_people", models.IntegerField()),
                ("count_by_role_type", models.JSONField()),
                ("count_by_role_status", models.JSONField()),
                ("count_by_accreditation_type", models.JSONField()),
                ("total_people_with_sub_units", models.IntegerField()),
                ("count_by_role_type_with_sub_units", models.JSONField()),
                ("count_by_role_status_with_sub_units", models.JSONField()),
                ("count_by_accreditation_type_with_sub_units", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="GroupSummaryRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Salute ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("total_people", models.IntegerField()),
                ("count_by_role_type", models.JSONField()),
                ("count_by_role_status", models.JSONField()),
                ("count_by_accreditation_type", models.JSONField()),
                ("total_people_with_sub_units", models.IntegerField()),
                ("count_by_role_type_with_sub_units", models.JSONField()),
                ("count_by_role_status_with_sub_units", models.JSONField()),
                ("count_by_accreditation_type_with_sub_units", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="SectionSummaryRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Salute ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("total_people", models.IntegerField()),
                ("count_by_role_type", models.JSONField()),
                ("count_by_role_status", models.JSONField()),
                ("count_by_accreditation_type", models.JSONField()),
                ("total_people_with_sub_units", models.IntegerField()),
                ("count_by_role_type_with_sub_units", models.JSONField()),
                ("count_by_role_status_with_sub_units", models.JSONField()),
                ("count_by_accreditation_type_with_sub_units", models.JSONField()),
            ],
        ),
        migrations.AlterModelOptions(
            name="teamsummaryrecord",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="teamsummaryrecord",
            name="idx_teamsummaryrecord_date",
        ),
        migrations.AddField(
            model_name="teamsummaryrecord",
            name="count_by_accreditation_type_with_sub_units",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teamsummaryrecord",
            name="count_by_role_status_with_sub_units",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teamsummaryrecord",
            name="count_by_role_type_with_sub_units",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teamsummaryrecord",
            name="total_people_with_sub_units",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="districtsummaryrecord",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="district_summary_records",
                to="hierarchy.district",
            ),
        ),
        migrations.AddField(
            model_name="groupsummaryrecord",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="group_summary_records",
                to="hierarchy.group",
            ),
        ),
        migrations.AddField(
            model_name="sectionsummaryrecord",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="section_summary_records",
                to="hierarchy.section",
            ),
        ),
        migrations.AddConstraint(
            model_name="districtsummaryrecord",
            constraint=models.UniqueConstraint(fields=("district", "date"), name="unique_district_summary_date"),
        ),
        migrations.AddConstraint(
            model_name="groupsummaryrecord",
            constraint=models.UniqueConstraint(fields=("group", "date"), name="unique_group_summary_date"),
        ),
        migrations.AddConstraint(
            model_name="sectionsummaryrecord",
            constraint=models.UniqueConstraint(fields=("section", "date"), name="unique_section_summary_date"),
        ),
    ]
