# Generated by Django 5.2.3 on 2026-01-17 19:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0004_add_unit_summary_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teamsummaryrecord",
            name="count_by_accreditation_type_with_sub_units",
        ),
        migrations.RemoveField(
            model_name="teamsummaryrecord",
            name="count_by_role_status_with_sub_units",
        ),
        migrations.RemoveField(
            model_name="teamsummaryrecord",
            name="count_by_role_type_with_sub_units",
        ),
        migrations.RemoveField(
            model_name="teamsummaryrecord",
            name="total_people_with_sub_units",
        ),
    ]
